// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/operations.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyByMarketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quantity     int64  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InstrumentId string `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	AccountId    string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *BuyByMarketRequest) Reset() {
	*x = BuyByMarketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyByMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyByMarketRequest) ProtoMessage() {}

func (x *BuyByMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyByMarketRequest.ProtoReflect.Descriptor instead.
func (*BuyByMarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{0}
}

func (x *BuyByMarketRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyByMarketRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *BuyByMarketRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Баланс позиции ценной бумаги.
type PositionsSecurities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Figi            string `protobuf:"bytes,1,opt,name=figi,proto3" json:"figi,omitempty"`                                                //Figi-идентификатор бумаги.
	Blocked         int64  `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`                                         //Количество бумаг заблокированных выставленными заявками.
	Balance         int64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`                                         //Текущий незаблокированный баланс.
	PositionUid     string `protobuf:"bytes,4,opt,name=position_uid,json=positionUid,proto3" json:"position_uid,omitempty"`               //Уникальный идентификатор позиции.
	InstrumentUid   string `protobuf:"bytes,5,opt,name=instrument_uid,json=instrumentUid,proto3" json:"instrument_uid,omitempty"`         //Уникальный идентификатор  инструмента.
	ExchangeBlocked bool   `protobuf:"varint,11,opt,name=exchange_blocked,json=exchangeBlocked,proto3" json:"exchange_blocked,omitempty"` //Заблокировано на бирже.
	InstrumentType  string `protobuf:"bytes,16,opt,name=instrument_type,json=instrumentType,proto3" json:"instrument_type,omitempty"`     //Тип инструмента.
}

func (x *PositionsSecurities) Reset() {
	*x = PositionsSecurities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionsSecurities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsSecurities) ProtoMessage() {}

func (x *PositionsSecurities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsSecurities.ProtoReflect.Descriptor instead.
func (*PositionsSecurities) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{1}
}

func (x *PositionsSecurities) GetFigi() string {
	if x != nil {
		return x.Figi
	}
	return ""
}

func (x *PositionsSecurities) GetBlocked() int64 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

func (x *PositionsSecurities) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PositionsSecurities) GetPositionUid() string {
	if x != nil {
		return x.PositionUid
	}
	return ""
}

func (x *PositionsSecurities) GetInstrumentUid() string {
	if x != nil {
		return x.InstrumentUid
	}
	return ""
}

func (x *PositionsSecurities) GetExchangeBlocked() bool {
	if x != nil {
		return x.ExchangeBlocked
	}
	return false
}

func (x *PositionsSecurities) GetInstrumentType() string {
	if x != nil {
		return x.InstrumentType
	}
	return ""
}

type PositionReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *PositionReportRequest) Reset() {
	*x = PositionReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionReportRequest) ProtoMessage() {}

func (x *PositionReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionReportRequest.ProtoReflect.Descriptor instead.
func (*PositionReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{2}
}

func (x *PositionReportRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type PositionReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Securities []*PositionsSecurities `protobuf:"bytes,1,rep,name=securities,proto3" json:"securities,omitempty"`
}

func (x *PositionReportResponse) Reset() {
	*x = PositionReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionReportResponse) ProtoMessage() {}

func (x *PositionReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionReportResponse.ProtoReflect.Descriptor instead.
func (*PositionReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{3}
}

func (x *PositionReportResponse) GetSecurities() []*PositionsSecurities {
	if x != nil {
		return x.Securities
	}
	return nil
}

type BuyByMarketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BuyByMarketResponse) Reset() {
	*x = BuyByMarketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyByMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyByMarketResponse) ProtoMessage() {}

func (x *BuyByMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyByMarketResponse.ProtoReflect.Descriptor instead.
func (*BuyByMarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{4}
}

func (x *BuyByMarketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_operations_proto protoreflect.FileDescriptor

var file_proto_operations_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x22,
	0x74, 0x0a, 0x12, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xfb, 0x01, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x67, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x67,
	0x69, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x69, 0x64, 0x12,
	0x29, 0x0a, 0x10, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x16, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x75, 0x74, 0x62, 0x6f,
	0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x22, 0x2d, 0x0a, 0x13, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0xaa, 0x01, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x75,
	0x79, 0x42, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c,
	0x2e, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75,
	0x74, 0x62, 0x6f, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x67, 0x2d, 0x62,
	0x6f, 0x74, 0x2d, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_operations_proto_rawDescOnce sync.Once
	file_proto_operations_proto_rawDescData = file_proto_operations_proto_rawDesc
)

func file_proto_operations_proto_rawDescGZIP() []byte {
	file_proto_operations_proto_rawDescOnce.Do(func() {
		file_proto_operations_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operations_proto_rawDescData)
	})
	return file_proto_operations_proto_rawDescData
}

var file_proto_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_operations_proto_goTypes = []interface{}{
	(*BuyByMarketRequest)(nil),     // 0: utbot.BuyByMarketRequest
	(*PositionsSecurities)(nil),    // 1: utbot.PositionsSecurities
	(*PositionReportRequest)(nil),  // 2: utbot.PositionReportRequest
	(*PositionReportResponse)(nil), // 3: utbot.PositionReportResponse
	(*BuyByMarketResponse)(nil),    // 4: utbot.BuyByMarketResponse
}
var file_proto_operations_proto_depIdxs = []int32{
	1, // 0: utbot.PositionReportResponse.securities:type_name -> utbot.PositionsSecurities
	0, // 1: utbot.OperationsService.BuyByMarket:input_type -> utbot.BuyByMarketRequest
	2, // 2: utbot.OperationsService.PositionReport:input_type -> utbot.PositionReportRequest
	4, // 3: utbot.OperationsService.BuyByMarket:output_type -> utbot.BuyByMarketResponse
	3, // 4: utbot.OperationsService.PositionReport:output_type -> utbot.PositionReportResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_operations_proto_init() }
func file_proto_operations_proto_init() {
	if File_proto_operations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_operations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyByMarketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionsSecurities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyByMarketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operations_proto_goTypes,
		DependencyIndexes: file_proto_operations_proto_depIdxs,
		MessageInfos:      file_proto_operations_proto_msgTypes,
	}.Build()
	File_proto_operations_proto = out.File
	file_proto_operations_proto_rawDesc = nil
	file_proto_operations_proto_goTypes = nil
	file_proto_operations_proto_depIdxs = nil
}
