// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/operations.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyByMarketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quantity     int64 `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InstrumentId int64 `protobuf:"varint,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
}

func (x *BuyByMarketRequest) Reset() {
	*x = BuyByMarketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyByMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyByMarketRequest) ProtoMessage() {}

func (x *BuyByMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyByMarketRequest.ProtoReflect.Descriptor instead.
func (*BuyByMarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{0}
}

func (x *BuyByMarketRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyByMarketRequest) GetInstrumentId() int64 {
	if x != nil {
		return x.InstrumentId
	}
	return 0
}

var File_proto_operations_proto protoreflect.FileDescriptor

var file_proto_operations_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x12,
	0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x32, 0x4e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x40, 0x0a, 0x0b, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x12, 0x19, 0x2e, 0x75, 0x74, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x75, 0x79, 0x42, 0x79, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x67, 0x2d, 0x62, 0x6f, 0x74, 0x2d, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2d,
	0x66, 0x65, 0x65, 0x64, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_operations_proto_rawDescOnce sync.Once
	file_proto_operations_proto_rawDescData = file_proto_operations_proto_rawDesc
)

func file_proto_operations_proto_rawDescGZIP() []byte {
	file_proto_operations_proto_rawDescOnce.Do(func() {
		file_proto_operations_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operations_proto_rawDescData)
	})
	return file_proto_operations_proto_rawDescData
}

var file_proto_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_operations_proto_goTypes = []interface{}{
	(*BuyByMarketRequest)(nil), // 0: utbot.BuyByMarketRequest
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_proto_operations_proto_depIdxs = []int32{
	0, // 0: utbot.Operations.BuyByMarket:input_type -> utbot.BuyByMarketRequest
	1, // 1: utbot.Operations.BuyByMarket:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_operations_proto_init() }
func file_proto_operations_proto_init() {
	if File_proto_operations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_operations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyByMarketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operations_proto_goTypes,
		DependencyIndexes: file_proto_operations_proto_depIdxs,
		MessageInfos:      file_proto_operations_proto_msgTypes,
	}.Build()
	File_proto_operations_proto = out.File
	file_proto_operations_proto_rawDesc = nil
	file_proto_operations_proto_goTypes = nil
	file_proto_operations_proto_depIdxs = nil
}
